class Throttle:
    def __init__(self,
                 default_throttle=.001,
                 connect=.1,
                 boot_instance=.05,
                 delete_instance=.01,
                 floating_ip_create=2,
                 floating_ip_attach=1,
                 floating_ip_delete=1,
                 floating_ip_list=1,
                 get_flavor_object=0,
                 get_image_object=0,
                 get_server_info=.2,
                 get_server_list=.3,
                 poll_status=1,
                 poll_ping=5,
                 poll_ssh=10,
                 status_check_delay=20,
                 ssh_check_delay=20,
                 bool_sync_requests=False,
                 bool_sync_float_ip=True,
                 bool_auto_throttle=False,
                 max_rps=1):
        self.default_throttle = default_throttle
        self.connect = connect
        self.boot_instance = boot_instance
        self.delete_instance = delete_instance
        self.floating_ip_create = floating_ip_create
        self.floating_ip_attach = floating_ip_attach
        self.floating_ip_delete = floating_ip_delete
        self.floating_ip_list = floating_ip_list
        self.get_flavor_object = get_flavor_object
        self.get_image_object = get_image_object
        self.get_server_info = get_server_info
        self.get_server_list = get_server_list
        self.poll_status = poll_status
        self.poll_ping = poll_ping
        self.poll_ssh = poll_ssh
        self.status_check_delay = status_check_delay
        self.ssh_check_delay = ssh_check_delay
        self.bool_sync_requests = bool_sync_requests
        self.bool_sync_float_ip = bool_sync_float_ip
        self.bool_auto_throttle = bool_auto_throttle
        self.max_rps = max_rps
